### ISSUE TITLE
openSUSE binary (request pending in OBS)

### ISSUE THREAD

**Issue by lbeltrame** [otakuto/crazydiskinfo#13]
This is just an issue to track this request:

https://build.opensuse.org/request/show/459603

I added an openSUSE spec to build CrazyDiskInfo for both openSUSE Tumbleweed and Leap 42.2.

**Comment by otakuto** [comment]
Thank you for your contribution.
@tSU-RooT will merge your request.

**Comment by tSU-RooT** [comment]
Hi, I am a maintainer at OBS.
I have merged your request now. 
Thanks!
