### ISSUE TITLE
CrazyDiskInfo shows wrong temperature about my SSD which doesn't have temperature info in S.M.A.R.T

### ISSUE THREAD

**Issue by BlueSkyDetector** [otakuto/CrazyDiskInfo#2]
My SSD temperature value is wrong value.
![crazy_temperature_01](https://cloud.githubusercontent.com/assets/210614/22143890/0b1a3288-df3f-11e6-9cc6-9cc9f966e9d2.png)

https://github.com/otakuto/CrazyDiskInfo/blob/master/main.cpp#L74
If sk_disk_smart_get_temperature() cannot get temperature info, it returns "-1".
So, it should check the return value.

Same things can happen about sk_disk_smart_get_power_cycle() and sk_disk_smart_get_power_on().

**Comment by BlueSkyDetector** [comment]
I made a workaround fix for this.
But using UINT64_MAX and -DBL_MAX for representing error. It's not good approach.
https://github.com/BlueSkyDetector/CrazyDiskInfo/tree/PR-show_values_as_na_if_it_doesnt_have_values

**Comment by otakuto** [comment]
Thank you for your report and PR.
Was this issue fixed with this commit?
e8d09408a301685506e61c1863b4636f2347f2c0

**Comment by BlueSkyDetector** [comment]
Thank you.
It works nicely.
Now I can get "-- °C" as temperature.
![crazy_temperature_02](https://cloud.githubusercontent.com/assets/210614/22190635/ec8ff3f4-e167-11e6-9434-b4a756fe74be.png)

BTW, there is a part remaining old color as following.
I made another PR for this. #4
![crazy_temperature_03](https://cloud.githubusercontent.com/assets/210614/22190712/8c6a3f88-e168-11e6-8f59-1064a6525e1b.png)
