### ISSUE TITLE
1.0.2 showing unstable behavior

### ISSUE THREAD

**Issue by hartwork** [otakuto/crazydiskinfo#22]
Hi!

Cool idea, definitely more fun than `smartctl`.

I'm running version 1.0.2. When I start `crazy`, one of three things happens:
* `Segmentation fault`
* Starts up showing `/dev/sda` (as good) and `/dev/sr0` (as bad), latter of which is my DVD drive
* Starts up showing `/dev/sda` (good) only (i.e. no `/dev/sr0`)

When I run `echo -n q | sudo crazy | fgrep /dev` in a loop, I can see all of these without waiting for long.

Besides the segfault, it would be cool if display was stable and the DVD drive would not be shown at all, at least not by default.

Thanks!

**Comment by hartwork** [comment]
On a side not, `libatasmart` seems to change its mind about `sr0` from time to time:
```
# sudo /usr/sbin/skdump /dev/sr0  # first take
Device: sat16:/dev/sr0
Type: 16 Byte SCSI ATA SAT Passthru
Size: 1023 MiB
Model: []
Serial: []
Firmware: [y !]
SMART Available: yes  <----
Quirks:
Awake: no
SMART Disk Health Good: Input/output error
Failed to dump disk data: Operation not supported

# sudo /usr/sbin/skdump /dev/sr0  # second take
Device: sat16:/dev/sr0
Type: 16 Byte SCSI ATA SAT Passthru
Size: 1023 MiB
Model: []
Serial: []
Firmware: [y !]
SMART Available: no  <----
Quirks:
Awake: no
ATA SMART not supported.
```

**Comment by monsieurp** [comment]
Hi @otakuto 

Gentoo users reported segmentation faults when compiling crazydiskinfo with GCC. However, for the record, I compiled it with clang and I cannot reproduce the segfault. The program starts and runs just fine. See https://bugs.gentoo.org/show_bug.cgi?id=629520 for more details.

**Comment by hartwork** [comment]
Here's a backtrace:
```
(gdb) bt
#0  0x00000000004099ae in attributeToHealth(Attribute const&) ()
#1  0x0000000000409abb in smartToHealth(SMART const&) ()
#2  0x0000000000409da7 in drawDeviceBar(_win_st*, std::vector<SMART, std::allocator<SMART> > const&, int) ()
#3  0x000000000040b611 in main::{lambda()#2}::operator()() const ()
#4  0x000000000040cbed in std::_Function_handler<void (), main::{lambda()#2}>::_M_invoke(std::_Any_data const&) ()
#5  0x000000000040ed36 in std::function<void ()>::operator()() const ()
#6  0x000000000040c171 in main ()
```

**Comment by monsieurp** [comment]
@otakuto ping?

**Comment by otakuto** [comment]
pong!
I'm sorry to have kept you waiting.
smartmontools support json output recently!
https://www.smartmontools.org/changeset/4640
Also, I will use smartctl as backend on 2.0.0.
So I think that this problem will be solved.
Thank you.

**Comment by monsieurp** [comment]
Thanks for the response. Looking forward to 2.0.0 then.

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
