### ISSUE TITLE
issue installing

### ISSUE THREAD

**Issue by killmasta93** [otakuto/crazydiskinfo#25]
hi,
trying to install but im getting this issue 
/usr/bin/ld: cannot find -ltinfow
collect2: error: ld returned 1 exit status
CMakeFiles/CrazyDiskInfo.dir/build.make:94: recipe for target 'crazy' failed
make[2]: *** [crazy] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/CrazyDiskInfo.dir/all' failed
make[1]: *** [CMakeFiles/CrazyDiskInfo.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alicektx** [comment]
...assuming debian / ubuntu, just edit -ltinfow to -ltinfo in CMakeLists.txt...
Or you could also try...
g++ -Wall -O2 -std=c++11 main.cpp -o crazy -latasmart -ltinfo -lncursesw

In lines 36-37 you can further change the bool values to your tastes / needs before building (ie. isRawHex(true)).

**Comment by killmasta93** [comment]
yep that did the trick
